kolyat:
  telegram-bot:
    bot-token: ${BOT_TOKEN}
    bot-username: ${BOT_USERNAME}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true